apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aqua-appset
spec:
  generators:
  - git:
      repoURL: https://github.com/jasonrwolfe/argo-app.git
      revision: HEAD
      directories:
      - path: clusters/eks/system/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jasonrwolfe/argo-app.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: 'system-{{path.basename}}'
      ignoreDifferences:
      - group: "admissionregistration.k8s.io"
        kind: "ValidatingWebhookConfiguration"
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
      - group: "admissionregistration.k8s.io"
        kind: "MutatingWebhookConfiguration"
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
      - group: "core"
        kind: "Secret"
        name: "aqua-kube-enforcer-certs"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
